server:
  port: 8080
spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${ORDER_SYS_KAFKA_SERVICE_HOST}:${ORDER_SYS_KAFKA_SERVICE_PORT}
    producer:
      client-id: order-service
    admin:
      auto-create: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
make-payment-url: http://${ORDER_SYS_BILLING_SERVICE_CHART_SERVICE_HOST}:8080/billing-service/makePayment
