server:
  port: 8080
spring:
  application:
    name: billing-service
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
